### ISSUE TITLE
EnjellyDownServices的构造函数参数导致EnjellyDownProvider无效

### ISSUE THREAD

**Issue by nickfan** [HavenShen/enjelly-down#1]
EnjellyDownServices的构造函数参数要求参数
`(Parser $parser)`

但EnjellyDownProvider的注册初始化流程时并未提供

**Comment by HavenShen** [comment]
@nickfan 谢谢，反馈。
忘记 new 的时候，依赖注入了。
已经修复了。

## EnjellyDownProvider.php 问题修复

头部引入 `Parser`

``` php
use HavenShen\EnjellyDown\Librarys\Parser;
```

实例化 `EnjellyDownServices` 注入 `Parser`

``` php
public function register()
{
    $this->app->bind('EnjellyDown', function($app){
        return new EnjellyDownServices(new Parser);
    });
}
```
